"""Add TeacherAbsenceNotification model

Revision ID: a89f0c2cfd27
Revises: 
Create Date: 2025-04-21 16:15:47.415583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89f0c2cfd27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_absence_notification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_absence_notification',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('faculty_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('period', sa.VARCHAR(length=50), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('notified_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
